servease/account/urls.py
from django.urls import path
from . import views 

app_name = 'account'

urlpatterns = [
	path('index/', views.index, name='index'),
	# path('<int:pk>/', views.detail, name="detail"),

]

servease/servease/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings 
from django.conf.urls.static import static

from pages import views

urlpatterns = [
    path('', views.landing_page, name='landing_page'),
    path('signup/', views.signup_page, name='sign_up'),
    path('login/', views.login_page, name='log_in'),
    path('logout/', views.logout_user, name='logout'),
    path('about/', views.about, name='about'), 
    path('mainpage/', views.main_page, name='main_page'),
    path('browse/', views.browse_page, name='browse'),
    #path('browse/', views.browse_page, name='service_detail'),
    path('services/', include('services.urls')),
    path('account/', include('account.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

servease/services/urls.py
from django.urls import path
from . import views 

app_name = 'service'

urlpatterns = [
	path('services/', views.services, name='services'), 
	path('new/', views.new, name='new'),
	path('<int:pk>/', views.detail, name="detail"),
	path('<int:pk>/delete/', views.delete, name="delete"),
	path('<int:pk>/edit/', views.edit, name="edit"),

]

servease/templates/about.html
{% extends 'main.html' %}
{% load static %}


{% block title %}About Us{% endblock %}

{% block content %}
<h1 class="text-center my-4">The Team</h1>


<div class="container justify-content-center">
    <div class="row justify-content-center">
        <div class="col-md-4 mb-4">
            <div class="card" style="width: 18rem;">
                <img src="{% static 'img/team1.jpg' %}" class="card-img-top" alt="...">
                <div class="card-body">
                    <h4 class="card-text">Jansen C. Solayao</h4>
                    <p class="card-text">Team Leader</p>
                </div>
            </div>
        </div>
        <div class="col-md-4 mb-4">
            <div class="card" style="width: 18rem;">
                <img src="{% static 'img/team3.png' %}" class="card-img-top" alt="...">
                <div class="card-body">
                    <h4 class="card-text">Eusedio T. Villato III</h4>
                    <p class="card-text">Sub-Leader</p>
                </div>
            </div>
        </div>
        <div class="col-md-4 mb-4">
            <div class="card" style="width: 18rem;">
                <img src="{% static 'img/team2.jpg' %}" class="card-img-top" alt="...">
                <div class="card-body">
                    <h4 class="card-text">Cyrine B. Malesido</h4>
                    <p class="card-text">Member</p>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="container">
    <div class="row">
        <div class="col-md-12 d-flex justify-content-center align-items-center" style="height: 300px;">
            <img src="{% static 'img/logo.png' %}" style="width: 300px;">
        </div>
    </div>
</div>

<div class="container mb-5">
	<h5 class="text-center mb-3">About ServEase</h5>
	<p class="text-center">
		ServEase is an event services booking app. This app was made with Bootstrap and Django for its backend. This app was made by Cyrine Malesido, Jansen Solayao, and Eusedio Villato III as part of their requirements for the subject, "Application Development & Emerging Technologies". These group of students are from Biliran Province State University enrolled in Bachelor of Science in Computer Science program under the School of Technology and Computer Studies.
	</p>
</div>



{% endblock %}

servease/templates/banner.html
{% extends 'main.html' %}

{% block title %}Welcome{% endblock %}

{% block content %}
{% load static %}

<div class="main-banner" id="top">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-6">
                <div class="left-content">
                    <div class="thumb">
                        <div class="inner-content">
                            <h4>We Are ServEase</h4>
                            <span>Book Event Services with Ease!</span>
                            <div class="main-border-button">
                                <a href="{% url 'browse' %}">Browse services now!</a>
                            </div>
                        </div>
                        <img src="{% static 'img/left-banner-image.png' %}" alt="">
                    </div>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="right-content">
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="right-first-image">
                                <div class="thumb">
                                    <div class="inner-content">
                                        <h4>Host</h4>
                                        <span>Find Hosts</span>
                                    </div>
                                    <div class="hover-content">
                                        <div class="inner">
                                            <h4>Host</h4>
                                            <p>Find Hosts According to Your Needs.</p>
                                            <div class="main-border-button">
                                                <a href="#">Discover More</a>
                                            </div>
                                        </div>
                                    </div>
                                    <img src="{% static 'img/baner-right-image-01.png' %}">
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="right-first-image">
                                <div class="thumb">
                                    <div class="inner-content">
                                        <h4>Catering</h4>
                                        <span>Find Catering Services</span>
                                    </div>
                                    <div class="hover-content">
                                        <div class="inner">
                                            <h4>Catering</h4>
                                            <p>Find Catering Services According to Your Taste.</p>
                                            <div class="main-border-button">
                                                <a href="#">Discover More</a>
                                            </div>
                                        </div>
                                    </div>
                                    <img src="{% static 'img/baner-right-image-02.png' %}">
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="right-first-image">
                                <div class="thumb">
                                    <div class="inner-content">
                                        <h4>Media</h4>
                                        <span>Find Creatives</span>
                                    </div>
                                    <div class="hover-content">
                                        <div class="inner">
                                            <h4>Media</h4>
                                            <p>Find Creatives Tailored to Your Vision.</p>
                                            <div class="main-border-button">
                                                <a href="#">Discover More</a>
                                            </div>
                                        </div>
                                    </div>
                                    <img src="{% static 'img/baner-right-image-03.png' %}">
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="right-first-image">
                                <div class="thumb">
                                    <div class="inner-content">
                                        <h4>Venue</h4>
                                        <span>Find Venues</span>
                                    </div>
                                    <div class="hover-content">
                                        <div class="inner">
                                            <h4>Venue</h4>
                                            <p>Find Venues That Suit Your Event.</p>
                                            <div class="main-border-button">
                                                <a href="#">Discover More</a>
                                            </div>
                                        </div>
                                    </div>
                                    <img src="{% static 'img/baner-right-image-04.png' %}">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- ***** Main Banner Area End ***** -->
{% endblock %}

servease/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>ServEase</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  </head>
  <body>
    
    {% block content %}
    {% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>

servease/templates/browse.html
{% extends 'main.html' %}

{% block title %}Browse{% endblock %}

{% block content %}

<div class="row">
	<div class="col-md-12 text-center mt-4">
    <h2>Newest Services</h2>
  </div>
  {% for service in services %}
    <div class="col-md-4 mb-4 mt-4">
      <div class="card h-100">
        <img src="{{ service.image.url }}" class="card-img-top" alt="{{ service.name}}-image">
        <div class="card-body d-flex flex-column">
          <h5 class="card-title">{{ service.name }}</h5>
          <h6 class="card-text mb-4" style="color: gray;">{{ service.category }}</h6>
          <p class="card-text">{{ service.description }}</p>
          <p class="card-text" style="color: #020269; font-size:12px; font-weight: bold;">Php {{ service.price|floatformat:2 }}</p>
          <a href="{% url 'service:detail' service.id %}" class="btn btn-primary mt-auto">View Details</a>
        </div>
      </div>
    </div>
    {% if forloop.counter|divisibleby:3 and not forloop.last %}
      </div><div class="row">
    {% endif %}
  {% endfor %}
</div>

<div class="row">
	<div class="col-md-12 text-center mt-4 mb-4">
    <h2>Categories</h2>
  </div>
  {% for category in categories %}
    <div class="col-md-3 mb-4">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">{{ category.name }}</h5>
          <p class="card-text">{{ category.service.count }} services available</p>
          <a href="{% url 'service:services' %}?query={{ query }}&category={{ category.id }}" class="btn btn-primary">Browse {{ category.name }}</a>
        </div>
      </div>
    </div>
    {% if forloop.counter|divisibleby:4 and not forloop.last %}
      </div><div class="row">
    {% endif %}
  {% endfor %}
</div>


{% endblock %}

servease/templates/footer.html
<footer class="footer mt-auto py-3 bg-dark text-light">
	<div class="container text-center">
	    <span>&copy; Future Forgers | 2023</span>
	</div>
</footer>

servease/templates/header.html
{% load static %}
<style>
    .custom-header {
    position: fixed; /* Keep it at the top */
    background-color: white; /* Change this to your desired background color */
    /* ... other styles ... */
}
</style>


<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<script>
$(document).ready(function() {
  // Get the current URL path
  var currentPath = window.location.pathname;

  // Find the corresponding link in the navigation and add the active class
  $('.navbar-nav a').each(function() {
    var href = $(this).attr('href');
    if (href === currentPath) {
      $(this).addClass('active');
    }
  });
});
</script>

<nav class="navbar navbar-expand-lg navbar-light bg-light header-sticky">
  <div class="container px-4 px-lg-5">
      <a href="" class="logo">
        <img src="{% static 'img/logo.png' %}" style="width: 128px;">
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
              <li class="nav-item"><a class="nav-link" aria-current="page" href="{% url 'browse' %}">Browse</a></li>
              <li class="nav-item"><a class="nav-link" href="{% url 'about' %}">About</a></li>
              <li class="nav-item"><a class="nav-link" href="{% url 'service:services' %}">Search</a></li>
              <li class="nav-item"><a class="nav-link" href="{% url 'account:index' %}">{{ request.user|capfirst }}'s Account</a></li>
              
          </ul>
          <div class="d-flex">
              <a class="btn btn-outline-danger" href="{% url 'logout' %}">Logout</a>
          </div>
      </div>
  </div>
</nav>

servease/templates/landing_page.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="container d-flex justify-content-center align-items-center vh-100">
	<img src="{% static 'img/logo.png' %}" alt="ServEase Logo" class="img-fluid mx-auto d-block" style="width: 500px;">
</div>

<div class="d-grid gap-2 col-3 mx-auto my-2">
  <button class="btn btn-primary" type="button">
  	<a href="{% url 'sign_up' %}" class="text-white" style="text-decoration: none;">Sign Up</a>
  </button>
  <button class="btn btn-primary" type="button">
  	<a href="{% url 'log_in' %}" class="text-white" style="text-decoration: none;">Log In</a>
  </button>
</div>

{% endblock %}

servease/templates/login_page.html
{% load static %}

<!DOCTYPE html>
<html>
    
<head>
	<title>ServEase | Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #d9f1fa !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #0a036b;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
			
		}

		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #024a11 !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
			border-radius: 10px;
		}
	</style>

</head>
<body>

	<div class="container">
	<img src="{% static 'img/logo.png' %}" alt="ServEase Logo" class="img-fluid mx-auto mt-5 pt-5 d-block" style="width: 200px;">
	</div>

	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">


					<h3 id="form-title">LOGIN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
						{% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							<input type="text" name="username" placeholder="Username..." class="form-control">
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
								<input type="password" name="password" placeholder="Password..." class="form-control" >
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
				   			</div>
					</form>

				</div>
				
				{% for message in messages %}
					<p id="messages">{{message}}</p>
				{% endfor %}

				<div class="mt-4">
					<div class="d-flex justify-content-center links" style="color: white;">
						Don't have an account? <a href="{% url 'sign_up' %}" class="ml-2">Sign Up</a>
					</div>
			
				</div>
			</div>
		</div>
	</div>
</body>

</html>

servease/templates/main.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>ServEase | {% block title %} {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.css' %}">

    <link rel="stylesheet" href="{% static 'css/templatemo-hexashop.css' %}">

    <link rel="stylesheet" href="{% static 'css/owl-carousel.css' %}">

    <link rel="stylesheet" href="{% static 'css/lightbox.css' %}">


    <link rel="icon" type="image/png" href="{% static 'img/title.png' %}">

    <style>
      .custom-div {
              padding-top: 100px; /* Adjust this value based on the height of your header */
            }

    </style>
  </head>
  <body>
    
    {% include 'header.html' %}
    
    <div class="container-fluid custom-div">
    {% block content %}
    
    {% endblock %}
    </div>
    {% include 'footer.html' %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>

servease/templates/navbar.html
{% load static %}

<style>
  .hello-msg{
    font-size: 18px;
    color: black;
    margin-right: 20px;
  }
</style>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class "dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
  </div>
  <span class="hello-msg">Hello, {{ request.user }}</span>
  <a href="{% url 'logout' %}" class="btn btn-outline-primary" style="margin-right: 10px;">Logout</a>
</nav>

servease/templates/signup_page.html
{% load static %}

<!DOCTYPE html>
<html>
    
<head>
	<title>ServEase | Sign Up</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #d9f1fa !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #0a036b;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
		}
		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #024a11 !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

	</style>

</head>
<body>

	<div class="container">
	<img src="{% static 'img/logo.png' %}" alt="ServEase Logo" class="img-fluid mx-auto mt-5 pt-5 d-block" style="width: 200px;">
	</div>

	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">
					<h3 id="form-title">REGISTER ACCOUNT</h3>
				</div>
				<div class="d-flex justify-content-center form_container">

					<form method="POST" action="">
						{% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							{{ form.username }}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-envelope-square"></i></span>
							</div>
							{{ form.email }}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{ form.password1 }}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{ form.password2 }}
						</div>

				   		<div class="d-flex justify-content-center mt-3 login_container">
				 			<input class="btn login_btn" type="submit" value="Register Account">
				   		</div>
					</form>
				</div>

				{{ form.errors }}
				
				<div class="mt-4">
					<div class="d-flex justify-content-center links" style="color: white;">
						Already have an account? <a href="{% url 'log_in' %}" class="ml-2">Login</a>
					</div>
				</div>
			</div>
		</div>
	</div>
	<script>
						/* Because i didnt set placeholder values in forms.py they will be set here using vanilla Javascript
		//We start indexing at one because CSRF_token is considered and input field 
		 */

		//Query All input fields
		var form_fields = document.getElementsByTagName('input')
		form_fields[1].placeholder='Username..';
		form_fields[2].placeholder='Email..';
		form_fields[3].placeholder='Enter password...';
		form_fields[4].placeholder='Re-enter Password...';


		for (var field in form_fields){	
			form_fields[field].className += ' form-control'
		}
	</script>
</body>
</html>