servease/account/urls.py
from django.urls import path
from . import views 

app_name = 'account'

urlpatterns = [
	path('index/', views.index, name='index'),
	# path('<int:pk>/', views.detail, name="detail"),

]

servease/servease/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings 
from django.conf.urls.static import static

from pages import views

urlpatterns = [
    path('', views.landing_page, name='landing_page'),
    path('signup/', views.signup_page, name='sign_up'),
    path('login/', views.login_page, name='log_in'),
    path('logout/', views.logout_user, name='logout'),
    path('about/', views.about, name='about'), 
    path('mainpage/', views.main_page, name='main_page'),
    path('browse/', views.browse_page, name='browse'),
    #path('browse/', views.browse_page, name='service_detail'),
    path('services/', include('services.urls')),
    path('account/', include('account.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

servease/services/urls.py
from django.urls import path
from . import views 

app_name = 'service'

urlpatterns = [
	path('services/', views.services, name='services'), 
	path('new/', views.new, name='new'),
	path('<int:pk>/', views.detail, name="detail"),
	path('<int:pk>/delete/', views.delete, name="delete"),
	path('<int:pk>/edit/', views.edit, name="edit"),

]

servease/services/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
class Category(models.Model):
	name = models.CharField(max_length=255)

	class Meta:
		ordering = ('name',)
		verbose_name_plural = 'Categories'


	def __str__(self):
		return self.name


class Service(models.Model):
	category = models.ForeignKey(Category, related_name='service',  on_delete=models.CASCADE)
	name = models.CharField(max_length=255)
	description = models.TextField(blank=True, null=True)
	price = models.FloatField()
	image = models.ImageField(upload_to='service_images', blank=True, null=True)
	is_sold = models.BooleanField(default=False)
	created_by = models.ForeignKey(User, related_name='service', on_delete=models.CASCADE)
	created_at = models.DateTimeField(auto_now_add=True)


	def __str__(self):
		return self.name

servease/services/forms.py
from django import forms 

from .models import Service

INPUT_CLASSES = 'form-control mb-2'

class NewServiceForm(forms.ModelForm):
	class Meta:
		model = Service 
		fields = ('category', 'name', 'description', 'price', 'image',)


		widgets = {
			'category': forms.Select(attrs={
				'class': INPUT_CLASSES
				}),
			'name': forms.TextInput(attrs={
				'class': INPUT_CLASSES
				}),
			'description': forms.Textarea(attrs={
				'class': INPUT_CLASSES
				}),
			# 'price': forms.TextInput(attrs={
			# 	'class': INPUT_CLASSES
			# 	}),
			'image': forms.FileInput(attrs={
				'class': INPUT_CLASSES
				}),
			}


		price = forms.FloatField(
	        widget=forms.NumberInput(attrs={'class': INPUT_CLASSES}),
	    )

class EditServiceForm(forms.ModelForm):
	class Meta:
		model = Service 
		fields = ('name', 'description', 'price', 'image', 'is_sold')
		
		widgets = {
			'name': forms.TextInput(attrs={
				'class': INPUT_CLASSES
				}),
			'description': forms.Textarea(attrs={
				'class': INPUT_CLASSES
				}),
			# 'price': forms.TextInput(attrs={
			# 	'class': INPUT_CLASSES
			# 	}),
			'image': forms.FileInput(attrs={
				'class': INPUT_CLASSES
				}),
			}


		price = forms.FloatField(
	        widget=forms.NumberInput(attrs={'class': INPUT_CLASSES}),
	    )

servease/services/views.py
from django.shortcuts import render, redirect,get_object_or_404
from django.contrib.auth.decorators import login_required
from django.db.models import Q


from .models import Service, Category
from .forms import NewServiceForm, EditServiceForm


# Create your views here.

def services(request):
	query = request.GET.get('query', '')
	services = Service.objects.filter(is_sold=False)
	categories = Category.objects.all()
	category_id = request.GET.get('category', 0)

	if query:
		services = services.filter(Q(name__icontains=query) | Q(description__icontains=query))


	if category_id:
		services = services.filter(category_id=category_id)


	return render(request, 'service/services.html', {
		'services': services,
		'query': query,
		'categories': categories,
		'category_id': int(category_id),
		})


def detail(request, pk):
	service = get_object_or_404(Service, pk=pk)
	related_services = Service.objects.filter(category=service.category, is_sold=False).exclude(pk=pk)[0:3]


	return render(request, 'service/detail.html', {'service': service, 'related_services': related_services})


@login_required
def new(request):
	if request.method == 'POST':
	    form = NewServiceForm(request.POST, request.FILES)

	    if form.is_valid():
	        service = form.save(commit=False)
	        service.created_by = request.user
	        service.save()  # Save the service instance to the database

	        return redirect('service:detail', pk=service.id)
	else:
	    form = NewServiceForm()  # Instantiate the form

	return render(request, 'service/form.html', {
	    'form': form,
	    'title': 'New Service'
	})


@login_required
def delete(request, pk):
	service = get_object_or_404(Service, pk=pk, created_by=request.user)
	service.delete()

	return redirect('account:index')


@login_required
def edit(request, pk):
    service = get_object_or_404(Service, pk=pk, created_by=request.user)

    if request.method == 'POST':
        form = EditServiceForm(request.POST, request.FILES, instance=service)
        if form.is_valid():
            form.save()

            return redirect('service:detail', pk=service.id)
    else:
        form = EditServiceForm(instance=service)

    return render(request, 'service/form.html', {
        'form': form,
        'title': 'Edit Service'
    })

servease/services/templates/service/detail.html
{% extends 'main.html' %}

{% block title %}{{service.name}}{% endblock %}

{% block content %}
  <div class="container pt-5 pb-5">
    <div class="row">
      <div class="col-md-6">
        <div class="card">
          <img src="{{ service.image.url }}" alt="{{ service.title }}" class="card-img-top rounded-right">
        </div>
      </div>
      <div class="col-md-6 mx-auto">
        <div class="card">
          <div class="card-body">
            <h2 style="font-weight: bold;">{{ service.name }}</h2>
            <h6 style="color: gray;">By {{ service.created_by.username }}</h6>
            <h4 class="my-4">Php{{ service.price|floatformat:2 }}</h4>

            {% if request.user == service.created_by %}
              <div class="mt-4 mb-4">
                <button type="button" class="btn btn-success">
                  <a href="{% url 'service:edit' service.id %}" class="text-white text-decoration-none">Edit</a>
                </button>
                <button type="button" class="btn btn-danger">
                  <a href="{% url 'service:delete' service.id %}" class="text-white text-decoration-none">Delete</a>
                </button>
              </div>
            {% else %}
              <a href="#" class="btn btn-primary my-5">Book Now</a>
            {% endif %}
            <p>{{ service.description }}</p>
          </div>
        </div>
      </div>
    </div>
  </div>


  <div class="row">
  <div class="col-md-12 text-center mt-4">
    <h2 class="mb-2">Related Services</h2>
  </div>
  {% for service in related_services %}
    <div class="col-md-4 mb-4 mt-4">
      <div class="card h-100">
        <img src="{{ service.image.url }}" class="card-img-top" alt="{{ service.name}}-image">
        <div class="card-body d-flex flex-column">
          <h5 class="card-title">{{ service.name }}</h5>
          <p class="card-text">{{ service.description }}</p>
          <p class="card-text" style="color: #020269; font-size:12px; font-weight: bold;">Php {{ service.price|floatformat:2 }}</p>
          <a href="{% url 'service:detail' service.id %}" class="btn btn-primary mt-auto">View Details</a>
        </div>
      </div>
    </div>
    {% if forloop.counter|divisibleby:3 and not forloop.last %}
      </div><div class="row">
    {% endif %}
  {% endfor %}
</div>
{% endblock %}

servease/services/templates/service/form.html
{% extends 'main.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}

<div class="container my-4">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card shadow-lg">
        <div class="card-body">
          <h2 class="card-title">{{ title }}</h2>
          <form method="POST" action="." enctype="multipart/form-data">
            {% csrf_token %}
            <div class="mb-3">
              {{form.as_p}}
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

servease/services/templates/service/services.html
{% extends 'main.html' %}

{% block title %}Search{% endblock %}

{% block content %}

<div class="container my-4">
  <div class="row">
    <div class="col-md-3 bg-primary-subtle pb-3 position-sticky" style="top: 0; height: 520px; border-radius: 10px;">
      <!-- Sidebar content -->
      <form method="GET" action="{% url 'service:services' %}">
        <div class="input-group mb-3 mt-3">
          <input type="text" class="form-control" placeholder="Find services..." value="{{ query }}" name="query">
          <button class="btn btn-outline-secondary">Search</button>
        </div>
      </form>

      <h2>Categories</h2>

      <ul class="list-group mt-3">
        <li class="list-group-item {% if category_id == 0 %}bg-success-subtle{% endif %}">
          <a href="{% url 'service:services' %}" class="list-group-item list-group-item-action list-group-item-primary">All Services</a>
        </li>
        {% for category in categories %}
        <li class="list-group-item{% if category.id == category_id %} bg-success-subtle{% endif %}">
          <a href="{% url 'service:services' %}?query={{ query }}&category={{ category.id }}" class="list-group-item list-group-item-action list-group-item-primary">{{ category.name }}</a>
        </li>
        {% endfor %}
      </ul>
    </div>

    <div class="col-md-9">
      <div class="row">
        {% for service in services %}
        <div class="col-md-4 mb-4">
          <div class="card h-100">
            <img src="{{ service.image.url }}" class="card-img-top" alt="{{ service.name }}-image">
            <div class="card-body d-flex flex-column">
              <h5 class="card-title">{{ service.name }}</h5>
              <p class="card-text">{{ service.description }}</p>
              <p class="card-text" style="color: #020269; font-size:12px; font-weight: bold;">Php {{ service.price|floatformat:2 }}</p>
              <a href="{% url 'service:detail' service.id %}" class="btn btn-primary mt-auto">View Details</a>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</div>

{% endblock %}